13.0 mig base comment template
OCA/account-invoice-reporting pull request #121
Opened 2019-10-19 16:44 UTC by emagdalenaC2i

2019-10-21 07:50 UTC, aheficent commented
It seems ci is red because of the pre-commit thing again

2019-10-21 11:13 UTC, emagdalenaC2i commented
@aheficent No, this time seems it is a 'proper' issue ;-) 
I will take a look later

2020-02-12 10:13 UTC, jimhoefnagels requested changes

2020-02-12 10:13 UTC, jimhoefnagels commented on base_comment_template/views/res_partner.xml
> +                <field name="property_comment_template_id" attrs="{'invisible': ['|',('customer', '=', False), ('is_company', '=', False), ('parent_id', '!=', False)]}"/>
```suggestion
                <field name="customer_rank" invisible="1"/>
                <field name="property_comment_template_id" attrs="{'invisible': ['|',('customer_rank', '=', 0), ('is_company', '=', False), ('parent_id', '!=', False)]}"/>
```

2020-02-12 10:13 UTC, jimhoefnagels commented on base_comment_template/__manifest__.py
> +    "depends": ["base"],
```suggestion
    "depends": ["account"],
```

2020-03-12 15:01 UTC, pedrobaeza commented on base_comment_template/models/res_partner.py
> +        company_dependant=True,
```suggestion
        company_dependent=True,
```
I have already fixed it in v12

2020-07-04 16:00 UTC, pedrobaeza commented
Superseded by #149

2020-07-04 16:00 UTC, closed without merging