[14.0] [MIG] partner_time_topay
OCA/account-invoice-reporting pull request #157
Opened 2020-10-23 23:28 UTC by JevinD

2021-04-14 16:45 UTC, bosd commented
Is this still a WIP?

2021-04-14 17:32 UTC, JevinD commented
@bosd I am not actively working on this. You can take over if needed.

2022-10-25 22:22 UTC, max3903 commented
@Urvisha-OSI Can you get this PR fixed and merged?

2022-10-26 19:02 UTC, rafaelbn commented
I can review functionally if you ping me @max3903 @Urvisha-OSI

2022-10-27 20:15 UTC, max3903 approved these changes

2022-10-30 17:57 UTC, bosd commented
@osi-scampbell Can you fix pre-commit on res_partner.xml ??

2022-10-30 18:13 UTC, bosd requested changes
Please fix pre-commit

2022-10-30 18:13 UTC, bosd commented on partner_time_to_pay/views/res_partner.xml
> +                <field name="d2p_ytd" groups="account.group_account_invoice"/>
plese fix pre-commit by adding a space at closing the tag
`_invoice"/>`
`_invoice" />`
(also on the other lines)

2022-10-31 10:15 UTC, Freni-OSI commented
@max3903 , It's ready for review. Mr. Travis :green_heart:

2022-10-31 10:25 UTC, bosd approved these changes
LGTM 👍

2022-11-02 19:24 UTC, rafaelbn commented
@max3903 what do you think if we add in this module a column (property hide) in invoices view lists with the date of the (last) payment which make full reconcile? Is something do you agree just in case? 😄 

Thanks

2022-11-02 19:29 UTC, rafaelbn approved these changes
Tested in runboat! 👍 

![imagen](https://user-images.githubusercontent.com/8736623/199584814-4b44f903-4402-4f7f-a4f8-1a14127460ed.png)

2022-11-02 19:30 UTC, rafaelbn commented
/ocabot merge patch

2022-11-02 19:41 UTC, merged