[14.0][FIX] account_invoice_report_grouped_by_picking: Remove priority and change position=replace in report_invoice.xml to prevent errors
OCA/account-invoice-reporting pull request #198
Opened 2021-05-27 11:23 UTC by victoralmau

Remote priority and change position=replace in report_invoice.xml to prevent errors.

According to https://github.com/OCA/account-invoice-reporting/pull/194#issuecomment-848506918 it's a good idea apply these change although in PR related is not necessary.

Please @joao-p-marques and @pedrobaeza can you review it?

2021-05-27 11:24 UTC, joao-p-marques approved these changes

2021-05-27 12:04 UTC, tafaRU approved these changes

2021-05-27 13:03 UTC, pedrobaeza commented
Travis is red

2021-05-27 14:01 UTC, victoralmau commented
Locked by '`account_comment_template`' https://github.com/OCA/account-invoice-reporting/pull/194 (that PR solves travis problem).

2021-05-28 05:47 UTC, pedrobaeza requested changes

2021-05-28 05:47 UTC, pedrobaeza commented on account_invoice_report_grouped_by_picking/views/report_invoice.xml
> +            <attribute name="invisible">True</attribute>
Is this working in qweb reports? I think you have to work with `display: None`, or put a `t-if="False"` clause for avoiding its visualization.

2021-05-28 06:45 UTC, pedrobaeza approved these changes

2021-05-28 06:45 UTC, pedrobaeza commented
/ocabot merge minor

2021-05-28 06:52 UTC, merged