[14.0][IMP] account_invoice_report_due_list: added outstanding amounts
OCA/account-invoice-reporting pull request #236
Opened 2022-09-10 09:45 UTC by dalonsod

With this improvement due list also shows outstanding amount for the existing dues:

e.g. for an already paid invoice:

![imagen](https://user-images.githubusercontent.com/12749832/189477976-8ff78b9f-017a-4546-a5c4-91d288b98474.png)

This PR implements #234

2022-09-14 16:46 UTC, dalonsod commented
Hello @victoralmau changes suggested in #234 made here.

Codecov is not passed, I don't know why (added extra test code for it, but it didn't seem to work), could you help me?

cc @carlosdauden

2022-09-14 16:58 UTC, dalonsod commented
Don't worry, finally I've found the problem and solved it.

Could you review? Thanks!!!

2022-09-19 07:07 UTC, victoralmau requested changes
Thanks for your contribution.

2022-09-19 07:07 UTC, victoralmau commented on account_invoice_report_due_list/tests/test_invoice_report_due_list.py
> +        cls.eur = cls.env.ref("base.EUR")
```suggestion
        usd = cls.env.ref("base.USD")
        eur = cls.env.ref("base.EUR")
        cls.currency = cls.env.ref("base.main_company").currency_id
        cls.currency_extra = eur if cls.currency == usd else usd
```

2022-09-19 07:07 UTC, victoralmau commented on account_invoice_report_due_list/tests/test_invoice_report_due_list.py
> +        self.assertEqual(invoice2.get_multi_due_list()[0][2], 50.0)
```suggestion
        move_form2 = Form(
            self.env["account.move"].with_context(default_move_type=move_type)
        )
        move_form2.partner_id = self.partner
        move_form2.invoice_payment_term_id = self.payment_term_multi
        with move_form2.invoice_line_ids.new() as line_form2:
            line_form2.product_id = self.product_id
            line_form2.price_unit = 200.0
        invoice2 = move_form2.save()
        invoice2.action_post()
        self.assertEqual(invoice2.get_multi_due_list()[0][2], 200.0)
        
   def test_due_list_currency_extra(self):
           move_form2 = Form(
            self.env["account.move"].with_context(default_move_type=move_type)
        )
        move_form2.partner_id = self.partner
        move_form2.invoice_payment_term_id = self.payment_term_multi
        move_form2.currency_id = self.currency_extra
        with move_form2.invoice_line_ids.new() as line_form2:
            line_form2.product_id = self.product_id
            line_form2.price_unit = 200.0
        invoice2 = move_form2.save()
        invoice2.action_post()
        self.assertEqual(invoice2.get_multi_due_list()[0][2], 50.0)
```

2022-09-19 09:24 UTC, dalonsod commented
Comments attended!

2022-09-19 09:55 UTC, carlosdauden approved these changes

2022-09-19 12:29 UTC, victoralmau approved these changes

2022-09-19 12:30 UTC, pedrobaeza commented
/ocabot merge major

Please fw-port it to v15

2022-09-19 12:46 UTC, merged

2022-09-22 14:57 UTC, dalonsod commented
> Please fw-port it to v15

#238 ready for reviews