[15.0[ [MIG] partner_time_to_pay + improvements
OCA/account-invoice-reporting pull request #249
Opened 2022-11-17 10:37 UTC by Shide

What i've done:
- All the base things on migrations
- Add a new field `full_reconcile_payment_date` on invoices to show when has been full reconciled
- Make all the fields on partner store true and computed based on his invoices and the `full_reconcile_payment_date` field
- Refactor and simplify the number of functions (and the lines of code to maintain) to compute the partner time to pay, using the `full_reconcile_payment_date` field
- Views for invoices
- Refactor tests completely and remove unnecesary lines
- Renamed `res_partner.xml` to `res_partner_view.xml`
- Add `es.po` and the `partner_time_to_pay .pot`
- Improved README.md to show what has been added

MT-1494 @moduon

@Murtaza-OSI @rafaelbn @bosd @agyamuta @max3903 @yajo feel free to review and suggest anything

This PR can be closed https://github.com/OCA/account-invoice-reporting/pull/232 because it's not bein maintained and this PR has a better performance (all stored true) and I'm going to fix and review as soon as possible anything it's wrong or you want to modify.

2022-11-17 11:37 UTC, yajo requested changes
In general, it works fine.

In runboat I couldn't see invoices when logging in as `demo` user. I'm not sure if that's because of this module, or maybe it's another one producing the problem. Could yo please check that?

Some comments below.

2022-11-17 11:37 UTC, yajo commented on partner_time_to_pay/readme/DESCRIPTION.rst
> +Also displays the full reconcile payment date on invoices
```suggestion
This module displays statistics related to the receivables and payables behavior of a partner on the *Sales & Purchase* tab of the partner form view.
Also displays the full reconcile payment date on invoices.
```

2022-11-17 11:37 UTC, yajo commented on partner_time_to_pay/readme/USAGE.rst
> +* Go to the Accounting tab of a partner
```suggestion
* Go to the *Sales & Purchase* tab of a partner
```

2022-11-17 11:37 UTC, yajo commented on partner_time_to_pay/readme/USAGE.rst
> +* There is 4 new fields. These fields represent the average days to pay for
```suggestion
* There are 4 new fields. These fields represent the average days to pay for
```

2022-11-17 11:37 UTC, yajo commented on partner_time_to_pay/readme/USAGE.rst
> +* Adds a new field to invoices to check the Full Reconcile Payment Date
```suggestion
* Adds a new field in the invoices form to check the Full Reconcile Payment Date
```

2022-11-17 11:37 UTC, yajo commented on partner_time_to_pay/models/res_partner.py
> +    )
Please add `help` on these fields. The names use some acronyms that might not be obvious at first sight.

2022-11-17 11:37 UTC, yajo commented on partner_time_to_pay/models/account_move.py
> +
```suggestion
        in_payment_states = {"paid", self._get_invoice_in_payment_state()}
```

2022-11-17 11:37 UTC, yajo commented on partner_time_to_pay/models/account_move.py
> +                        payments and payments[0].date or fields.Date.today()
A little trick that does the same:

```suggestion
                        payments[:1].date or fields.Date.today()
```

2022-11-17 12:19 UTC, Shide commented
> In general, it works fine.
> 
> In runboat I couldn't see invoices when logging in as `demo` user. I'm not sure if that's because of this module, or maybe it's another one producing the problem. Could yo please check that?
> 
> Some comments below.

Suggestions applied.
I've enter on another runboat from a month ago and when i'm entering as demo in invoices, happens as well

2022-11-17 13:36 UTC, max3903 commented
/ocabot migration partner_time_to_pay

2022-11-17 13:38 UTC, max3903 approved these changes

2022-11-17 18:50 UTC, rafaelbn reviewed
Functionall test in runboat 👍 

Please review my comments before merging

![imagen](https://user-images.githubusercontent.com/8736623/202532739-9705acf5-1625-4c85-8cb2-44d31a186905.png)

2022-11-17 18:50 UTC, rafaelbn commented on partner_time_to_pay/README.rst
> +
I think the work is enough to be here, please add Moduon, thanks.

2022-11-17 18:50 UTC, rafaelbn commented on partner_time_to_pay/README.rst
> +* Jevin Dement <jdement@opensourceintegrators.com>
We have contribute too please Edu, both.

2022-11-17 18:50 UTC, rafaelbn commented on partner_time_to_pay/README.rst
> +    :alt: max3903
add me here please , this will informe me so I can test changes

2022-11-17 18:52 UTC, max3903 commented on partner_time_to_pay/__manifest__.py
> +    "maintainers": ["max3903"],
```suggestion
    "maintainers": ["max3903", "rafaelbn"],
```

2022-11-18 08:49 UTC, Shide commented
@rafaelbn @max3903 everything changed :)

2022-11-18 14:11 UTC, rafaelbn approved these changes
👍

2022-11-18 14:23 UTC, fcvalgar approved these changes
Functional Review ok

2022-11-18 14:42 UTC, rafaelbn commented
/ocabot merge patch

2022-11-18 14:48 UTC, merged