[16.0][MIG] account_invoice_report_payment_info: Migration to version 16.0
OCA/account-invoice-reporting pull request #270
Opened 2023-04-12 14:43 UTC by stefan-tecnativa

cc @Tecnativa TT42418

@CarlosRoca13 please review!

2023-04-18 07:25 UTC, CarlosRoca13 requested changes

2023-04-18 07:25 UTC, CarlosRoca13 commented on account_invoice_report_payment_info/models/account_invoice.py
> +        res = super()._get_reconciled_info_JSON_values()
This method does not exist anymore. So this is no having effect. 

Check where is the data collected on the report to replicate the behaviour.

2023-05-02 15:00 UTC, CarlosRoca13 reviewed
It works, but I'm not sure if the code is achieving the same result as in the latest versions.

Can you confirm @carlosdauden

2023-05-07 06:18 UTC, sergio-teruel approved these changes
Functional and code review ok

2023-05-14 05:44 UTC, sergio-teruel commented
ping @juangomezzurita

2023-05-15 06:00 UTC, CarlosRoca13 approved these changes

2023-05-15 06:02 UTC, pedrobaeza commented
/ocabot merge nobump

2023-05-15 06:03 UTC, pedrobaeza commented
/ocabot migration account_invoice_report_payment_info

2023-05-15 08:11 UTC, merged