[ADD] partner_daytopay
OCA/account-invoice-reporting pull request #53
Opened 2017-04-20 23:04 UTC by max3903

2017-05-22 19:30 UTC, lasley requested changes
Thanks @max3903 - comments inline

2017-05-22 19:30 UTC, lasley commented on partner_daytopay/README.rst
> +============
Can remove sections without specific instructions

2017-05-22 19:30 UTC, lasley commented on partner_daytopay/models/res_partner.py
> +                            (datetime.strptime(payment.payment_date,
`fields.Datetime.from_string` instead of datetime

2017-05-22 19:30 UTC, lasley commented on partner_daytopay/models/res_partner.py
> +    d2p_life = fields.Float(compute=_compute_dtp_life,
Move field declarations to top

2017-05-22 19:30 UTC, lasley commented on partner_daytopay/models/res_partner.py
> +            for invoice in invoice_ids:
These computation methods are duplicating a lot of logic and should be unified or abstracted

2017-05-22 19:30 UTC, lasley commented on partner_daytopay/models/res_partner.py
> +    d2p_ytd = fields.Float(compute=_compute_dtp_ytd,
Use strings for compute method

2017-05-22 19:44 UTC, max3903 commented on partner_daytopay/models/res_partner.py
> +            for invoice in invoice_ids:
@bodedra Can you help me on this? Thanks!

2017-05-25 15:02 UTC, jcdrubay requested changes
I don't understand how this code works for lifetime; it seems to me that it will always only compute ytd indicators.

Maybe basic automatic tests would highlight this with 3 invoices:
 invoice 1 for partner 1 this year
 invoice 2 for partner 2 this year
 invoice 3 for partner 3 last year

2017-05-25 15:02 UTC, jcdrubay commented on partner_daytopay/views/res_partner.xml
> +                    <field name="credit" modifiers="{'readonly': true}"/>
Why do you need this? This is a function field without inverse right and therefore already readonly, right? Maybe we could have a comment to explain why in the code?

2017-05-25 15:02 UTC, jcdrubay commented on partner_daytopay/models/res_partner.py
> +            if fields.Date.from_string(invoice.date_invoice).year ==\
With this if, it will always be YTD and never lifetime.

2017-05-25 15:02 UTC, jcdrubay commented on partner_daytopay/models/res_partner.py
> +    def _compute_dtp_ytd(self):
Exactly the same code as _compute_dtp_life

2017-05-26 13:29 UTC, jcdrubay commented
You could create a unique compute function for all fields `_compute_d2x`

Also, I would refactor so that we only loop once per invoice type. Here is a suggestion...

```
    def _compute_d2x(self):
        for partner in self:
            partner.d2p_ytd, partner.d2p_life = \
                self._compute_d2x_per_invoice_type(partner, 'out_invoice')
            partner.d2r_ytd, partner.d2r_life = \
                self._compute_d2x_per_invoice_type(partner, 'in_invoice')

    def _compute_d2x_per_invoice_type(self):

        this_year = datetime.now().year
    
        total_number_of_invoices_life = 0
        total_number_of_invoices_ytd = 0

        total_days_to_pay_life = 0
        total_days_to_pay_ytd = 0

        for invoice in self._get_invoice_ids(partner.id, invoice_type):

            invoice_year = fields.Date.from_string(invoice.date_invoice).year
 
            date_due = fields.Date.from_string(invoice.date_invoice)

            days_to_pay_invoice = self._get_invoice_payment(
                    invoice.payment_ids, date_due)

            total_number_of_invoices_life += 1
            total_days_to_pay_life += days_to_pay_invoice
 
            if invoice_year == this_year:
                total_number_of_invoices_ytd += 1 
                total_days_to_pay_ytd += days_to_pay_invoice

        d2x_ytd = days_to_pay_ytd / number_of_invoices_ytd
        d2x_life = days_to_pay_life / number_of_invoices_life
        
        return d2x_ytd, d2x_life
```

2017-05-30 06:09 UTC, jcdrubay requested changes
Minor optimization suggestion

2017-05-30 06:09 UTC, jcdrubay commented on partner_daytopay/models/res_partner.py
> +                d2x_ytd = total_days_to_pay_ytd / total_number_of_invoices_ytd
This should be outside the for loop because we only need to calculate once.

2017-05-30 06:09 UTC, jcdrubay commented on partner_daytopay/models/res_partner.py
> +            d2x_life = total_days_to_pay_life / total_number_of_invoices_life
This should be outside the for loop because we only need to calculate once.

2017-05-31 00:55 UTC, jcdrubay requested changes

2017-05-31 00:55 UTC, jcdrubay commented on partner_daytopay/models/res_partner.py
> +                d2x_ytd = total_days_to_pay_ytd / total_number_of_invoices_ytd
and we should have a little check to avoid division by 0 after bringing it outside the loop :)

2017-05-31 00:55 UTC, jcdrubay commented on partner_daytopay/models/res_partner.py
> +            d2x_life = total_days_to_pay_life / total_number_of_invoices_life
and we should have a little check to avoid division by 0 after bringing it outside the loop :)

2017-06-08 18:09 UTC, vprime approved these changes
Looks good

2017-06-26 14:19 UTC, merged

2017-06-26 14:32 UTC, jcdrubay commented
@max3903 I am surprised that you merged without 3 approvals. Also I am not sure if you have seen my last 2 comments. If you did then I guess I was  mistaken. Anyway, I think that it is a nice contribution :)

2017-06-26 14:51 UTC, max3903 commented
@jcdrubay I am sorry I didn't see your comments. Fixed in #59. Yes I merged without 2 approvals because this PR had been opened for almost a month...