[ADD] account_invoice_report_due_list: New module
OCA/account-invoice-reporting pull request #68
Opened 2018-03-16 13:57 UTC by carlosdauden

WIP: Missed tests

@Tecnativa

2018-03-16 19:16 UTC, pedrobaeza requested changes
Add in the roadmap to add tests

2018-03-16 19:16 UTC, pedrobaeza commented on account_invoice_report_due_list/README.rst
> +This module extends the functionality of account to show multiple due data
This module extends the invoice report for adding information about the corresponding due dates and amounts.

2018-03-16 19:16 UTC, pedrobaeza commented on account_invoice_report_due_list/README.rst
> +#. Go to Account > Invoices
Does this exist?

2018-03-16 19:16 UTC, pedrobaeza commented on account_invoice_report_due_list/README.rst
> +#. Select or create an invoice with a multiple lines payment term
Select or create a payment term with multiple term lines.

2018-03-16 19:16 UTC, pedrobaeza commented on account_invoice_report_due_list/i18n/es.po
> +msgstr "Fechas vencimiento"
`Fechas de vencimiento`

2018-03-16 19:16 UTC, pedrobaeza commented on account_invoice_report_due_list/i18n/es.po
> +msgstr "Fecha vencimiento múlitiple"
Múltiples fechas de vencimiento

2018-03-16 19:16 UTC, pedrobaeza commented on account_invoice_report_due_list/README.rst
> +  * Carlos Dauden
Add line break in between for correct RST syntax

2018-03-16 19:16 UTC, pedrobaeza commented on account_invoice_report_due_list/models/account_invoice.py
> +                lambda ml: ml.account_id.id == self.account_id.id
You shouldn't filter this way (and `.id` part is  useless), but filter the same as Odoo does: by account type according invoice type (in_*: payable, out_*: receivable).

2018-03-16 19:16 UTC, pedrobaeza commented on account_invoice_report_due_list/views/account_invoice_view.xml
> +            <attribute name="groups"/>
Why resetting groups attribute?

2018-03-31 11:14 UTC, pedrobaeza commented
@carlosdauden please check my comments

2018-04-01 05:50 UTC, feketemihai commented
@carlosdauden @pedrobaeza will you take in consideration the amounts that need to be paid on dates, it will be a good improvement, something like in https://github.com/OCA/account-invoicing/pull/348 but more accurate since that pr didn't threat Invoicing in different currency..

2018-04-01 11:13 UTC, pedrobaeza commented
@feketemihai indeed this doesn't take into account if the invoice is in other currency.

@carlosdauden please change the PR for using `amount_currency` instead of balance when `currency_id` of the account.move.line is different from `invoice_id.company_id.currency_id`.

2018-05-19 18:35 UTC, pedrobaeza commented
@carlosdauden please finish this

2018-11-12 17:01 UTC, rafaelbn commented
This PR has been in customer  production environment for 8 months without any issue I think is not WIP

2018-11-12 17:01 UTC, rafaelbn approved these changes
Functionally speaking :+1:

2018-12-04 23:05 UTC, pedrobaeza approved these changes

2018-12-04 23:06 UTC, merged