[10.0][FIX] account_invoice_production_lot: only compute stock.production.lot related to move done
OCA/account-invoice-reporting pull request #84
Opened 2018-10-09 10:48 UTC by tafaRU

This patch fixes the following use case scenario.

Steps to reproduce:

* create a new product 'Product Test': stockable and tracking by lots
* update its quantity to 3 with new lot 'Lot1'
* update its quantity to 3 with new lot 'Lot2'
* sale 4 of 'Product Test'
* on the delivery, split the lots and set To Do quantities as 3 for Lot1 and leave 0 for Lot2
* validate the delivery and create a backorder

Current behavior:

the field 'Production Lots' of the invoice generated is filled with both lots and, consequently,
the invoice report will also contain info related to the lot not delivered yet.

Expected behavior:

the invoice report only contains info related to the lot involved in the delivery, which is Lot1.

2018-10-09 11:14 UTC, SimoRubi requested changes
Code review

2018-10-09 11:14 UTC, SimoRubi commented on account_invoice_production_lot/models/account_invoice.py
> +                lambda move: move.state == 'done').lot_ids
Note that if there are multiple done moves, this gets an error: you should retrieve `lot_ids` using `mapped`.
Moreover, maybe it is more readable if you split all this in a few lines.

2018-10-09 11:14 UTC, SimoRubi commented on account_invoice_production_lot/tests/test_invoice_production_lot.py
> +        self.assertEqual(len(line.prod_lot_ids.ids), 1)
Why don't you assert that this is the lot you want using its `id`?

2018-10-09 11:14 UTC, SimoRubi commented on account_invoice_production_lot/tests/test_invoice_production_lot.py
> +        self.assertIn('Lot 1', line.lot_formatted_note)
Looking at the usecase you described, here you should also assert that `'Lot 2'` is not in `line.lot_formatted_note`.
Anyway you can just skip this assertion if in the line above you check using the lot's `id`.

2018-10-09 11:14 UTC, SimoRubi commented on account_invoice_production_lot/tests/test_invoice_production_lot.py
> +        self.assertEqual(len(line.prod_lot_ids.ids), 2)
Same remarks as previous test's

2018-10-09 12:29 UTC, tafaRU commented
@SimoRubi, done in https://github.com/OCA/account-invoice-reporting/pull/84/commits/26d051d3487c1c96a91c49e25ceab553a754ab2b Thanks!

2018-10-09 15:38 UTC, SimoRubi commented
@tafaRU what about the tests?
Why don't you check the lots using their `id` instead of `self.assertIn('Lot 1', line.lot_formatted_note)`?
Wouldn't that be more straightforward?

2018-10-09 15:51 UTC, tafaRU commented
@SimoRubi, I checked both conditions, isn'it?
I'd prefer kept that one related to `lot_formatted_note` in order to also check the string used in the invoice report.

2018-10-09 16:19 UTC, SimoRubi commented
Ok I thought you had experienced some trouble in comparing the `id`s instead of comparing the strings, but if it's just your choice then ok.
Anyway tested this in runbot and it works!
Thanks for your contribution

2018-10-09 16:20 UTC, SimoRubi approved these changes
Tested in Runbot too

2018-10-10 07:45 UTC, tafaRU commented
> The remarks of my previous still stand

@SimoRubi, It seems to me they have been already addressed in https://github.com/OCA/account-invoice-reporting/commit/26d051d3487c1c96a91c49e25ceab553a754ab2b

**test_01_sale_stock_delivery_partial_invoice_product_lot**
```
self.assertEqual(line.prod_lot_ids.id, self.lot1.id)
```

**test_02_sale_stock_delivery_partial_invoice_product_lot**
```
self.assertIn(self.lot1.id, line.prod_lot_ids.ids)
self.assertIn(self.lot2.id, line.prod_lot_ids.ids)
```
Isnt'it?

2018-10-11 13:52 UTC, tafaRU commented
Superseded by https://github.com/OCA/account-invoice-reporting/pull/85

2018-10-11 13:53 UTC, tafaRU commented
@SimoRubi, thank you for your review.
Could you also please review https://github.com/OCA/account-invoice-reporting/pull/85?

2018-10-11 13:53 UTC, closed without merging